- name: Setup Docker on all nodes
  hosts: all
  become: yes
  roles:
    - docker_setup

- name: Deploy Backend pada backend_nodes
  hosts: backend_nodes
  become: yes
  roles:
    - backend_deployment
